server:
  port: 8080

spring:
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  application:
    name: origami-system-biz

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3

security:
  ignore-list:
    - /register
    - /kaptcha
    - /sms/phone-code
    - /error
    - /**
  sms-login-enabled: true
  kaptcha-enabled: false

captcha:
  arithmetic-captcha-enabled: false

sms:
  sms-code-length: 6

logging:
  level:
    org.origami: debug
    springfox.documentation: error

